### PR TITLE
#409: AmazonSQSAsyncClient does not have constructor taking a Request…

### PR DESCRIPTION
**Pull request by muellerc**
…MetricCollector

### CODE REVIEW

**Comment by shorea** [comment]
Can you take a look at https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSAsyncClientBuilder.java. We are trying to encourage use of the builders over the constructors.

**Comment by muellerc** [comment]
Ok, will do.
Should I revert the constructor changes or should I only add the builder changes?

**Comment by shorea** [comment]
The builder already supports it.

**Comment by muellerc** [comment]
Ok, fine. Shouldn't we close the issue in this case? Or is there still something to do which I miss?

**Comment by shorea** [comment]
Sure, sounds good to me. If the builders don't work out for your use case feel free to open another issue.

**Comment by jpaterso** [comment]
The builder pattern doesn't allow overriding the client's behaviour around shutdown, specifically waiting for the the executor service to terminate. Is there any way around this?

**Pull request closed without merging**
