### PR TITLE
Add us-east-1 to S3 Regions

### LINKED ISSUE #1411: US-East-1 Missing from S3 Regions (was hard to find reference that US_Standard should be used)
http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html indicates that S3 does run in us-east-1, but you won't find an enum value here: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java#L69

This page indicates that us-east-1 is US_Standard: http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

Might be nice to mention this in the docs somehow.

### PR DESCRIPTION
**Pull request by timcharper**
Fixes #1411

### CODE REVIEW

**Comment by varunnvs92** [comment]
There is no official us-east-1 endpoint for s3. The global endpoint (s3.amazonaws.com) is considered to the us-east-1 endpoint. That region is represented by [US_Standard](https://github.com/timcharper/aws-sdk-java/blob/8640e2d6ee1d3dbee1215a252de5b3241bf3c606/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/Region.java#L57) enum value.

**Comment by timcharper** [comment]
I was wondering if that might be the case but [the S3 Introduction docs](http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html) persuaded me otherwise.

Okay, then a note in the docs might be nice for future people that stumble here?

**Comment by varunnvs92** [comment]
If you check the note [here](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region), you will find "Amazon S3 renamed the US Standard Region to the US East (N. Virginia) Region". When s3 is launched, us-east-1 is represented by US standard which is what the SDK represented in the enum value. Even though S3 changed their documentation, we can't use a new value in our enums as it is a breaking change for existing customers.

**Comment by timcharper** [comment]
K, closing; updating the issues link with a potential doc improvement.

**Pull request closed without merging**
