### PR TITLE
maven-compiler-plugin 3.6.0

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
has anybody reviewed this?

**Comment by shorea** [comment]
Looks fine to me. Just curious, but what is the motivation for upgrading?

**Comment by sullis** [comment]
when I opened pom.xml in Intellij, the Intellij editor reported an error for maven-compiler-plugin.  The error disappears when I set the version number to 3.6.0

**Comment by sullis** [comment]
can you merge this?

**Pull request merged**
