### PR TITLE
fix incorrect 'x-amz-grant-full-control' header

### LINKED ISSUE #1346: 'x-amz-grant-full-control' header is passed incorrectly
When I put an object to S3 with FullControl permission for a canonical id using Java SDK, The SDK adds escape double quotes around the ID. So, the request is as follows and it is rejected. 

```
"s3:x-amz-grant-full-control": "id=\"qwertyuiop\""
```

Request from CLI or Python SDK does not have escape double quotes around the ID, then request is accepted.

```
"s3:x-amz-grant-full-control": "id="qwertyuiop"
``` 

This might cause the issue.
https://github.com/aws/aws-sdk-java/blob/51428ab65a35a309c7853e91401f40f456d5b159/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L1614-L1615

### PR DESCRIPTION
**Pull request by yohei1126**
fix #1346

### CODE REVIEW

**Comment by dagnir** [comment]
LGTM. I'll pull this in upstream.

**Comment by dagnir** [comment]
Thanks for the contribution!

**Comment by yohei1126** [comment]
thanks! could you merge it? I want to use it once it gets released.

**Comment by dagnir** [comment]
@yohei1126 I'll merge this in once it's merged upstream; this repo isn't actually used to master the SDK release; it simply contains the latest released code 😄

**Comment by yohei1126** [comment]
OK, thanks!

2017年10月18日(水) 6:52 Dongie Agnir <notifications@github.com>:

**Comment by yohei1126** [comment]
#1346 was closed so I also close this PR.

**Pull request closed without merging**
