### PR TITLE
updated plugins for Reproducible Builds (excl osgi)

### PR DESCRIPTION
**Pull request by hboutemy**
aws-java-sdk-osgi is the only remaining non-reproducible module, waiting
for Felix maven-bundle-plugin improvement

see https://maven.apache.org/guides/mini/guide-reproducible-builds.html for more information on how to configure a Maven build to get Reproducible Build

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hboutemy** [comment]
with second commit, fixing the OSGI reproducibility issue, aws-sdk-java becomes fully reproducible
@debora-ito @millems

**Comment by hboutemy** [comment]
@debora-ito @millems  it would be nice to add aws-sdk-java to https://github.com/jvm-repo-rebuild/reproducible-central

**Comment by millems** [comment]
What are the relative merits of enabling reproducible builds for v1? We're generally hesitant to take PRs for v1, because it's a lot of effort to import into our internal build system, particularly when it affects our pom.xml files that are mostly generated.

We'd rather spend the time on v2: https://github.com/aws/aws-sdk-java-v2/

**Comment by hboutemy** [comment]
Reproducible Builds merits are for any OSS used as binary https://reproducible-builds.org/

I did a PR for v2 some time ago https://github.com/aws/aws-sdk-java-v2/pull/1759

Given we all have much to do, I can understand some form of prioritization

**Pull request closed without merging**
