### PR TITLE
Make javax.mail dependency optional for OSGi bundle

### LINKED ISSUE #1915: OSGi bundle javax mail dependency
When trying to use the AWS SDK OSGi bundle, we get this error:

```
caused by: Unable to resolve com.amazonaws.aws-java-sdk-osgi/1.11.480: missing requirement [com.amazonaws.aws-java-sdk-osgi/1.11.480] osgi.wiring.package; filter:="(osgi.wiring.package=javax.mail)"]]
```

according to the pom, there is no dependency to this package.
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-osgi/1.11.480

is this dependency no longer needed and just by accident in the META-INF/Manifest.MF?
Or could it maybe made optional (I assume SES might use it?)

### PR DESCRIPTION
**Pull request by CodingFabian**
In the good tradition to fix your own issues:
This should fix #1915

### CODE REVIEW

**Comment by dagnir** [comment]
Change looks good to me. Thanks for the contribution! Can you confirm you're submitting this under the [Apache 2.0 license](https://github.com/aws/aws-sdk-java/blob/master/LICENSE.txt)?

**Comment by CodingFabian** [comment]
Sure, can be integrated under Apache 2. Any special CLA to sign or is a comment good enough?

**Comment by dagnir** [comment]
Thanks. No CLA necessary for this update (see https://github.com/aws/aws-sdk-java/blob/master/CONTRIBUTING.md).

**Comment by dagnir** [comment]
This is now shipped in 1.11.528. Thanks again for the contribution!

**Pull request merged**
