### PR TITLE
Added type overrides to the cargs in decider registration

### PR DESCRIPTION
**Pull request by nterry**
This allows consumers to use polymorphism in constructor
resolution, rather than the literal built-in type resolution

This is needed to overcome a Java limitation

### CODE REVIEW

**Comment by nterry** [comment]
@hanshuo-aws @david-at-aws @shorea I really need this fix. Mocks in unit tests are subclasses, and thus the current stuff isn't quite enough...

So the failures are due to some weird issues:
OracleJDK7:

The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: PermGen space

OpenJDK6:

testRequestTimeoutEnforcedWithRetries(com.amazonaws.http.AmazonHttpClientRequestTimeoutTest): The request timeout feature is only available for Java 1.7 and above.
  testRequestTimerCancelledTask(com.amazonaws.http.AmazonHttpClientRequestTimeoutTest): The request timeout feature is only available for Java 1.7 and above.
  testResponseNotBufferedForStreamingOperation(com.amazonaws.http.AmazonHttpClientRequestTimeoutTest): The request timeout feature is only available for Java 1.7 and above.

**Comment by shorea** [comment]
The build failures are fine, we've got a fix for the Java6 build staged internally. I've engaged the SWF team to get their opinion on the change.

**Comment by nterry** [comment]
Fantastic! What's your gut feeling on an ETA?

**Comment by shorea** [comment]
Unfortunately the SWF team doesn't have the bandwidth to look at this until next week. Is it feasible to install this in a local repo until then so you're not blocked?

**Comment by nterry** [comment]
@shorea Maybe, but the design might change due to feedback from the swf team... Its not super critical, so i can wait a week or so... I was just looking for some idea of timeframe. Thanks!

Any expedition you could do would be appreciated though ;)

**Comment by nterry** [comment]
@shorea Any updates?

**Comment by shorea** [comment]
Hey @nterry, a SWF engineer had time to evaluate this PR. His response is below.


Hi Terry,

I'm reluctant to change the interface of this class just to solve this problem. I'd rather find a way to perform the type resolution.

I think https://docs.oracle.com/javase/7/docs/api/java/beans/Expression.html is a good candidate to solve this problem, see example code below:

import java.beans.Expression;

public class Test {
    public static void main(String[] args) throws Exception {
        A a = new B();
        // C newInstance = C.class.getDeclaredConstructor(a.getClass()).newInstance(a);
        C newInstance = (C) new Expression(C.class, "new", new Object[]{a}).getValue();

        System.out.println(newInstance.getClass().getName());
    }

    public static class A {}
    public static class B extends A {}
    public static class C {
        A a;

        public C(A a) {
            this.a = a;
        }
    }
}

I tested it on my laptop and it works on Java6, 7 and 8.

I didn't know java.beans.Expression before so I'd like to do a little bit of research (~1h) before we go ahead and use it in Flow. But, if you are ok with it, I think it's the way to go.

Could you please test this approach with your own code and Java setups?

Thank you (sorry for the delay),
Luc

**Comment by nterry** [comment]
Hey, no problem man! I didn't know about that lib either! I'll work it in
and re-submit. I'll admit, this solution seemed a little ugly to me too.

**Comment by nterry** [comment]
@shorea Please inform Luc that Ive implemented the 'fix'

**Comment by shorea** [comment]
Will do!

**Comment by shorea** [comment]
Merging in Pull request. Thanks for the contribution!

**Comment by nterry** [comment]
@shorea Did you perform the merge manually? I dont see it in master's history

**Comment by shorea** [comment]
Hmm not sure what I did. Looks like I closed the PR instead of merging it. Can you revive your branch so I can reopen? May need to open another PR, not sure.

**Comment by nterry** [comment]
Ok, just a sec

**Comment by nterry** [comment]
Im rebasing to master again and ill push once more in like 20 mins or so

**Comment by shorea** [comment]
Sure thing. I apologize for the inconvenience.

**Comment by nterry** [comment]
Ok, see #572

**Comment by shorea** [comment]
Thanks!

**Pull request closed without merging**
