### PR TITLE
Make KeyManagerFactory agnostic of JRE provider

### LINKED ISSUE #2390: Please make KeyManager agnostic of JRE provider.
AWS core has "SunX509" as a hard-coded Key Manager option.
https://github.com/aws/aws-sdk-java/blob/9dd9b354da6957e6e00e857765fd7a64e8ee4b7f/aws-java-sdk-core/src/main/java/com/amazonaws/http/AbstractFileTlsKeyManagersProvider.java#L43

## Describe the bug
Using the API on IBM JRE where:
ssl.KeyManagerFactory.algorithm=IbmX509
will fail to create Key Manager.

## Expected Behavior
choosing the default key manger would let users use other options, for example ibmX509.

## Current Behavior
Using the API on IBM JRE where:
ssl.KeyManagerFactory.algorithm=IbmX509
will fail to create Key Manager.

## Possible Solution
KeyManagerFactory KMF = KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());
should fix this.

## Context
I am trying to use the AWS API, running on IBM JRE. getting errors when SunX509 is not found.

## Your Environment

* AWS Java SDK version used: 1.11.825
* JDK version used: java version "1.8.0_241", IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200124_438197 (JIT enabled, AOT enabled)
* Operating System and version: Red Hat Enterprise Linux Server release 7.6

### PR DESCRIPTION
**Pull request by JogoShugh**
* Fixes #2390
* This simply pulls the default algorithm rather than asking for the hard-coded "SunX509"

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dagnir** [comment]
Hey @JogoShugh thanks for the PR! This change looks fine to me, I'll work on pulling it upstream.

**Comment by JogoShugh** [comment]
Great, thank you!

**Comment by dagnir** [comment]
Once it's merged upstream, it will go out with the following SDK release. I will update this PR when that happens, but since it's a small change it should be pretty quick, probably within a day or two.

**Comment by dagnir** [comment]
This change was merged upstream and will go out with the next release. Thanks!

**Pull request merged**
