### PR TITLE
"connection" header should be removed as it is changed to "keep-alive…

### PR DESCRIPTION
**Pull request by ttwd80**
…" regardless of the value sent

### CODE REVIEW

**Comment by breedloj** [comment]
Hey, thanks for the PR!  As a matter of fact we just got a PR yesterday that should achieve the same thing: https://github.com/aws/aws-sdk-java/pull/669  This is being merged in for our next scheduled release (should be today).  Please let me know if there is still something additionally you'd like to see changed.

Thanks!

**Comment by breedloj** [comment]
Ah, looking at this closer this looks like a more comprehensive change to the signer vs. the other PR which only affects S3.  Let me check and see if it makes sense to include both of these changes.

**Comment by shorea** [comment]
Can you confirm you are submitting under Apache 2.0?

**Comment by ttwd80** [comment]
Yes. Submitting under Apache 2.0.

**Comment by shorea** [comment]
Thanks for the contribution. This will be included in our release later today.

**Pull request merged**
