### PR TITLE
Compatibility with JRE 9: make Base64 work without jaxb

### PR DESCRIPTION
**Pull request by VladRassokhin**
Also includes same change as in #1526

With this PR it would be possible to use aws-sdk-java on JRE 9 without additional options like `--add-modules`. We need that because we use same scripts to run our app on Java 1.6 - 9, so it's impossible to pass some additional arguments to java executable depending on its version.

### CODE REVIEW

**Comment by VladRassokhin** [comment]
Rebased onto master

**Comment by VladRassokhin** [comment]
@spfink could you please review/merge this one as well? 
Not sure why GitHub shows merge conflict as I've rebased branch onto master and force-pushed branch.

**Comment by VladRassokhin** [comment]
@shorea Sorry for disturbing, could you please take a look?

**Comment by shorea** [comment]
@VladRassokhin yes apologies, I'll take a look. Can you confirm you are submitting under the Apache 2.0 license?

**Comment by VladRassokhin** [comment]
@shorea Apache2 is fine, should I sign some CLA?

**Comment by shorea** [comment]
Nope just written confirmation is fine. Merging, thanks for the contribution! We'll likely have a release of this next week.

**Comment by VladRassokhin** [comment]
Thanks!

**Pull request merged**
