### PR TITLE
Added doesObjectExist(String bucketName, String objectName) in AmazonS3Client

### PR DESCRIPTION
**Pull request by matteprl**
Since there is no way (at least what I am aware of) checking if object exists in bucket I decided to implement my own. I am using listObjects(String bucketName) to obtain objects and check for matching names.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@matteprl Instead call `AmazonS3.getObjectMetadata` and handle the exception?

**Comment by shorea** [comment]
+1 to using getObjectMetadata. Could you also revert the formatting changes. It's making the diff hard to verify. 

Can you confirm you are submitting under the apache 2.0 license in the comments of the PR.

**Comment by matteprl** [comment]
@shorea @andrewgaul Hey guys. Sure, I can rewrite it to use `getObjectMetadata` as you suggest, and fix formatting. I will try to do it till end of this workweek. Thank You for suggestions.

**Comment by shorea** [comment]
Let me know when this is ready for review. Github doesn't have notifications when new diffs are available.

**Comment by matteprl** [comment]
@shorea It took my few days more to get a spare hour to clean this Pull Request.

>Can you confirm you are submitting under the apache 2.0 license in the comments of the PR.
Yes. I am submitting those changes under apache 2.0 license.

**Comment by shorea** [comment]
Change looks good. As far as naming goes how about doesObjectExist, I think the InBucket is implied by having bucketName as a parameter.

**Comment by matteprl** [comment]
> think the InBucket is implied by having bucketName as a parameter.
@shorea I agree. So one commit more.

**Comment by shorea** [comment]
Awesome, thanks! Got an internal CR for the change I've got to get approved then after that I'll merge this in. Thanks for the contribution!

**Comment by matteprl** [comment]
No problem. This is my first OSS contribution, so Im probably overreacting
this - but hell, this feels awesome.

Pozdrawiam,
Mateusz Lisik

2016-01-27 23:43 GMT+01:00 Andrew Shore <notifications@github.com>:

**Comment by shorea** [comment]
That's great to hear! We love getting pull requests!

**Comment by shorea** [comment]
Merging PR. Thanks again for the contribution! This will be available in the next SDK release.

**Comment by jgangemi** [comment]
any time frame on the next sdk release? i'd like to use this new functionality.

thanks!!

**Comment by shorea** [comment]
We've got one tentatively scheduled for Monday.

**Pull request merged**
