### PR TITLE
Expose instance signature through EC2MetadataUtils

### PR DESCRIPTION
**Pull request by slandelle**

### CODE REVIEW

**Comment by slandelle** [comment]
Failing tests have nothing to do with this PR.

**Comment by shorea** [comment]
Thanks for the contribution! I'll merge this in a few hours after our release finishes.

**Comment by shorea** [comment]
Merged, thanks again! This will be available in our next release, probably tomorrow or early next week.

**Comment by slandelle** [comment]
Great, thanks!

**Comment by slandelle** [comment]
It looks like it didn't make it in 1.11.371. Looking forward to next release :)

**Pull request merged**
