### PR TITLE
Update joda-time version in pom.xml

### PR DESCRIPTION
**Pull request by tabladrum**
*Issue #, if available:*

*Description of changes:*
Updated joda-time version in pom.xml. 2.8.1 is too old.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by debora-ito** [comment]
Hi @tabladrum apologies for the long silence.

Is there any security alerts on the current joda-time version, or are you suggesting we upgrade because it's old?

**Comment by tabladrum** [comment]
Thanks @debora-ito for the quick response. There is no security alert. But 2.8.1 is way too old (2015).

**Comment by brianwarner** [comment]
Hi @debora-ito, I'm on Topo's team. For a little more context, our internal process looks at the age of a component, and the older a dependency is, the harder it is for our devs to justify its use. Bumping a few versions would help a number of people out. Thanks for the consideration!

**Comment by yamelsenih** [comment]
Maybe is related to: https://github.com/aws/aws-sdk-java/pull/2586

**Comment by tabladrum** [comment]
Happy new year @debora-ito - any feedback on this PR?

**Comment by debora-ito** [comment]
Happy New Year!

I brought this up to the team and they are interested in upgrading the joda-time version, but based on some past experiences with joda-time we need to work on writing additional integration tests to make sure nothing will break. The task is in the backlog, pending prioritization.

@tabladrum any particular reason to upgrade to version `2.11.2` when there's newer versions available?

**Comment by tabladrum** [comment]
2.12.0...2.12.2 came out after I submitted this PR. Will be good to take the latest.

**Comment by tabladrum** [comment]
@debora-ito Updated joda-time to 2.12.1

**Comment by tabladrum** [comment]
Also let me know if I can hep anyway in creating the additional test cases.

**Comment by tabladrum** [comment]
Pinging again :-)

**Comment by debora-ito** [comment]
@tabladrum @brianwarner @cmxconsulting 

The joda-time version was upgraded as part of SDK `1.12.704` release.
https://github.com/aws/aws-sdk-java/blob/4066cae126e509d6da49001afce1baee6a7b2459/pom.xml#L431

**Pull request closed without merging**
