### PR TITLE
Fetched field name using PropertyDescriptor to fix fields with upper …

### PR DESCRIPTION
**Pull request by ghost**
…case starting letter.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jiveshthreja** [comment]
Had a requirement where we are saving data with the key for e.g. CONTACT_US
This automatically changes to cONTACT_US while saving in the dynamo due to the method fieldNameOf in StandardBeanProperties.
Sent it as a default name and fetched using java.beans.PropertyDescriptor

**Comment by jiveshthreja** [comment]
Can someone from AWS review and merge ?

**Comment by jiveshthreja** [comment]
@debora-ito I see you active on other PR's hence tagging for review.

**Comment by jivesh-threja** [comment]
Shows ghost PR as had to merge GitHub accounts.
PR created by @jivesh-threja

**Comment by debora-ito** [comment]
We don't have plans to merge this change. Closing this as a stale PR.

**Pull request closed without merging**
