### PR TITLE
fixing typo 

### PR DESCRIPTION
**Pull request by sergioescala**
Fixing typo, replacing EventSoure for EventSource

### CODE REVIEW

**Comment by varunnvs92** [comment]
Please confirm that you are submitting the PR under Apache 2.0 license?

**Comment by sergioescala** [comment]
Yes, I'm submitting the PR under Apache 2.0 license

**Comment by varunnvs92** [comment]
Thanks for confirming. This will be included in next release.

**Comment by varunnvs92** [comment]
@sergioescala 
I apologize that I didn't realize this is a change in lambda client. These docs are generated and provided by the service team. We need to make this change internally. I will cut a ticket to the service to make the change. There will be a bit of delay to make the final change.

**Comment by sergioescala** [comment]
@varunnvs92 no problem!

**Pull request merged**
