### PR TITLE
fix unsafe publishes in Copy/UploadMonitor

### PR DESCRIPTION
**Pull request by amrasarfeiniel**

### CODE REVIEW

**Comment by amrasarfeiniel** [comment]
@hansonchar not sure if you're who i should be bugging about PRs, but this has been sitting open for over 2 weeks now and should probably get fixed due to its (small but nonzero) potential to cause weird and hard to debug issues.

**Comment by hanshuo-aws** [comment]
Hey @amrasarfeiniel . Again can you confirm the Apache 2.0 license before I merge this?
The change looks good!

**Comment by amrasarfeiniel** [comment]
Yep, Apache 2.0 is good by me.  Thanks!

**Comment by hanshuo-aws** [comment]
Change has been merged. Thanks for the contribution!

**Pull request merged**
