### PR TITLE
Added ability to specify constructor args to Workflow workers

### PR DESCRIPTION
**Pull request by nterry**
This allows for better dependency injection, especially for injecting
mocks for testing client code.

### CODE REVIEW

**Comment by nterry** [comment]
@david-at-aws The sooner i can get this reviewed, the better. I rally need this ;)

**Comment by nterry** [comment]
Also, just for the legal mumbo jumbo: I'm contributing under the Apache 2.0 license

**Comment by hanshuo-aws** [comment]
Merged. Thanks for the contribution @nterry !

**Comment by nterry** [comment]
No, thank you!!

**Pull request merged**
