### PR TITLE
#701 Added ClientConfiguration to Cloud Watch Metrics configurations

### PR DESCRIPTION
**Pull request by gauravbrills**
CloudWatchMetricConfig - added ClientConfiguration depedency to be used for setting client params
MetricUploaderThread - Now uses ClientConfiguration to construct aws cloudwatch client
DefaultMetricCollectorFactory - Now uses client configuration

### CODE REVIEW

**Comment by zhangzhx** [comment]
Hi @gauravbrills , Thanks for contributing to AWS SDK for Java. This PR looks good to me and will be published in our next release. Can you confirm that the update is under Apache License 2?

**Comment by gauravbrills** [comment]
@zhangzhx yes it is . also I think there could be a possible enhancement to AmazonCloudWatchClient  with more fluent builders but that is for another time ; a possible PR and enhancement candidate .

**Comment by zhangzhx** [comment]
Looking forward to the PR :)

**Comment by shorea** [comment]
"AmazonCloudWatchClient with more fluent builders"

We are looking to do exactly this as well! If you are interested we may be able to arrange an informal private beta to get some feedback on the API.

**Comment by gauravbrills** [comment]
@shorea sure can check it out

**Comment by gauravbrills** [comment]
@shorea @zhangzhx shall I raise a ticket or issue to track "AmazonCloudWatchClient with more fluent builders" PR

**Pull request merged**
