### PR TITLE
Fix for a few typos

### PR DESCRIPTION
**Pull request by EronHennessey**
A few typo fixes in a couple of DynamoDB javadocs.

### CODE REVIEW

**Comment by varunnvs92** [comment]
@EronHennessey 
Thanks for your PR. Please confirm that you are submitting under Apache 2.0 license?

**Comment by EronHennessey** [comment]
Um, yeah. I also work @amazon.

**Comment by EronHennessey** [comment]
Clicked the wrong button.

**Comment by varunnvs92** [comment]
@EronHennessey 
We are in same team :P 
Just wanted to make sure that we have license info mentioned in the comments.

**Comment by EronHennessey** [comment]
Yes, the license is in comments at the top of the file.

**Comment by varunnvs92** [comment]
Will be included in tomorrow's release. Thanks!

**Comment by EronHennessey** [comment]
Thank you!

**Pull request merged**
