### PR TITLE
Implement AccessControlList.equals

### PR DESCRIPTION
**Pull request by andrewgaul**
Also implement `hashCode` and add missing `@Override` annotations.

### CODE REVIEW

**Comment by shorea** [comment]
Can you confirm you are submitting under apache 2.0 license? 

Also these were generated correct?

**Comment by andrewgaul** [comment]
Confirmed that I submit this change under the Apache 2.0 license.

These were not generated; I wrote these and copied the style from `com.amazonaws.services.s3.model.Grant`.  I can rewrite this in a more idiomatic style if the SDK has helpers equivalent to Java 7 `Objects.equals`.

**Comment by shorea** [comment]
I'll merge this in tomorrow.

**Comment by shorea** [comment]
Thanks again for the contribution! This will be included in the next release of the SDK.

**Pull request merged**
