### PR TITLE
Added 'le', 'lt', 'ge', 'gt' and 'between' methods to the S PathOperand (Fix for #592)

### PR DESCRIPTION
**Pull request by ihalila**
I straight-up copypasted the le/lt/ge/gt and between methods from N.java because as far as I can see they should work as-is. Did a quick test to confirm that they work, though I didn't find any unit-tests to add to. Fixes issue #592

### CODE REVIEW

**Comment by manikandanrs** [comment]
Thanks for the pull request. The PR looks good. 

We are working on getting the tests code out. We have unit tests for Xspec internally which I am going to run to make sure the PR doesn't break anything.

If you wish to submit an unit test I will get them merged as well.

**Comment by ihalila** [comment]
Thanks for checking the PR out. I don't have a suitable test to include though, my tests are part of an integration test and I can't easily extract them into anything useful here.

**Comment by manikandanrs** [comment]
Thanks. Can you confirm if you are submitting under Apache 2.0 license.

**Comment by ihalila** [comment]
Yes, I can confirm I'm submitting under the Apache 2.0 license.

**Comment by manikandanrs** [comment]
Thanks for the contribution. This is staged for our next release.

**Pull request merged**
