### PR TITLE
Fix for the MalformedPolicy error code on custom policy with null ipRange

### PR DESCRIPTION
**Pull request by handokochen**
Fix for the MalformedPolicy error code when passing a null to the optional ipRange variable in getCookiesForCustomPolicy method.

### CODE REVIEW

**Comment by varunnvs92** [comment]
Thanks for the Pull request. Can you confirm you are submitting this under the Apache 2.0 license?

**Comment by handokochen** [comment]
Yes, I confirm that I'm submitting this under the Apache 2.0 license.

**Comment by varunnvs92** [comment]
This change looks good. I'll run this by the team and hopefully get it in to our next staged release which is  tomorrow. Thanks!

**Comment by varunnvs92** [comment]
@handokochen 
Hey there was another PR that modified different code in buildCustomPolicy method. I merged that PR before yours and now your pr shows that it have conflicts. I apologize for that. However I copied your changes internally and will be included in today's release.

If you are okay with me internally changing the code, you can ignore this message. Otherwise can you pull latest code from master and submit your PR again? Sorry for the inconvenience. It would be great if you can submit the modified PR by today evening before SDK release.

Thanks!

**Comment by varunnvs92** [comment]
@handokochen 
Sorry that this change was not included in today's release. If you can update the PR, I will make sure that this will be included in Thursday's release. Thank you.

**Comment by handokochen** [comment]
I'll make that change tomorrow. Thank you.

**Comment by varunnvs92** [comment]
@handokochen 
I have merged your PR. No changes required from your side. Sorry for the confusion.

Thanks for your contribution.

**Comment by handokochen** [comment]
Awesome. Thank you.

**Pull request merged**
