### PR TITLE
LambdaInvokeFactory supporting lambda names from a map

### PR DESCRIPTION
**Pull request by codan84**
The issue this PR aims to address is [described here](https://github.com/aws/aws-sdk-java/issues/602)

### CODE REVIEW

**Comment by shorea** [comment]
I think it would be simpler and more flexible just to take an override for the name rather then a map. The caller can then choose between pulling the name from a map, loading it from some external configuration source, or computing it dynamically from some context. Also we can probably avoid a subclass of the invocation handler and just pass the derived function name (whether that comes from the annotation or the override) into the handler class. It seems very possible that we will add more overrides and configuration options in the future so I think it would be prudent to wrap the function name override in some kind of configuration object (LambdaInvokerFactoryConfig for example) so that we can easily add fields to it without having an explosion of build method overloads, Similiar to what we do with the DynamoDBMapper (http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapper.html#DynamoDBMapper%28com.amazonaws.services.dynamodbv2.AmazonDynamoDB,%20com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapperConfig%29).

**Comment by codan84** [comment]
Hi Andrew, I have looked at [DynamoDBMapperConfig.TableNameOverride](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.TableNameOverride.html) and indeed this seems like a better approach. I will work on a similar solution.

**Comment by shorea** [comment]
Yeah I actually wasn't thinking about this in particular but I like your idea better.

Few comments inline
LambdaNameResolver -> LambdaFunctionNameResolver

Rename method and add some additional context params. The default resolver would just use the class and grab the annotation. A custom one might do something fancier.
getName(String key) -> getFunctionName(Class<?> clzz, LambdaInvokerFactoryConfig config)

Could you also confirm you are submitting this under the Apache 2.0 license?

**Comment by codan84** [comment]
Sounds like a plan. I will try to work on this today. And yes, I will do it under Apache 2.0.

**Comment by codan84** [comment]
I think the work is done, unless you have some further comments :)

**Comment by shorea** [comment]
Change looks good, we've got a release going now but I'll get this merged in and staged for the next release.

**Comment by shorea** [comment]
This has been merged. Thanks for the contribution! This will be available in the next release of the SDK.

**Comment by shorea** [comment]
@codan84, we have a release scheduled for later today but unfortunately this change won't be included as I screwed up and didn't stage it correctly. The diff for today will look like this is being removed but that's just an artifact of how we publish changes to Github. We will have another release of the SDK next week that will add these changes back in and make them publicly available. I apologize for the inconvenience. We are excited for these changes though, I think customers will find a lot of value in it.

**Comment by codan84** [comment]
@shorea Will this make it to 1.10.51? And do you know when is the release planned? We could really do with this functionality... Cheers.

**Comment by shorea** [comment]
Yep we've got a release tentatively scheduled for today.

**Comment by strokine** [comment]
LambdaInvokerFactoryConfig is depricated

**Comment by shorea** [comment]
Check out the new builder.

https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-lambda/src/main/java/com/amazonaws/services/lambda/invoke/LambdaInvokerFactory.java#L110

**Comment by AzeemBOL** [comment]
Great... Worked for me.

**Comment by meeza** [comment]
great.. worked for me.

**Pull request merged**
