### PR TITLE
aws-java-sdk-core: EC2MetadataClient.java - Fix sending of a User-Agent

### PR DESCRIPTION
**Pull request by muhqu**
Builds upon #1562 by @willbengtson. 

- [x] Adds Unit Tests to verify the SDK User-Agent is added to metadata requests
- [x] Fix missing SDK User-Agent, when custom retry policy is used.

/cc @varunnvs92

### CODE REVIEW

**Comment by muhqu** [comment]
The build failure seems unrelated…
> `[ERROR]   The project com.amazonaws:aws-java-sdk-osgi:1.11.377-SNAPSHOT (/home/travis/build/aws/aws-sdk-java/aws-java-sdk-osgi/pom.xml) has 1 error`
> `[ERROR]     Unresolveable build extension: Plugin org.apache.felix:maven-bundle-plugin:2.5.3 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.felix:maven-bundle-plugin:jar:2.5.3: Could not transfer artifact org.apache.felix:maven-bundle-plugin:pom:2.5.3 from/to central (https://repo.maven.apache.org/maven2): Received fatal alert: protocol_version -> [Help 2]`

**Comment by dagnir** [comment]
@muhqu Thanks! Can you confirm you're submitting this under the terms of the [Apache 2.0 License](https://github.com/aws/aws-sdk-java/blob/master/LICENSE.txt)?

**Comment by muhqu** [comment]
@dagnir sure! I confirm, I’m submitting this under the terms of the Apache 2.0 License.

**Comment by dagnir** [comment]
Thanks for confirmation. Our release today has already begun, so this change will be part of the next upcoming release.

**Pull request merged**
