### PR TITLE
Add an overload to TransferManager.copy(...) with a 'metadata' parameter

### PR DESCRIPTION
**Pull request by spew**
When performing a cross region copy it is desirable to use an AmazonS3Client for the destination region. If one uses the source region as their S3 client then an AmazonS3Exception is thrown telling the client to re-direct to the correct endpoint. This is handled by S3V4AuthErrorRetryStrategy but it is slow and causes a constant stream of error messages to be printed to the console about the redirection:

  "please use region-specific endpoint to access ... buckets located in regions that require V4 signing."

Today, the TransferManager.copy(...) method requires that the source region S3 be used because of a call to fetch the ObjectMetadata in the copy  method. This getObjectMetadata request must be made with an S3Client pointing at the source region. This commit adds an overload which allows the user to pass in the metadata and thus use a TransferManager with a destination S3 client.

### CODE REVIEW

**Comment by shorea** [comment]
How do you feel about an overload that takes an instance of AmazonS3 instead for any service calls that need to be made to the destination region?

**Comment by spew** [comment]
shorea: that works too! So the actual "AmazonS3.copyObject(...)" request would be made to the destination in that case but the objectMetadata would be retrieved from the source region using the default s3 client?

**Comment by shorea** [comment]
Good question. Maybe it makes more sense to pass in the client of the source region and use the transfer manager's client for the actual copy object. Since the exposed API is copy I think I'd expect it to use for TF's client for the copy. Open for negotiation though, I think either approach would be fine.

**Comment by spew** [comment]
No problem with either, I agree passing in the source client for the metadata operation is better (your second suggestion).

**Comment by manikandanrs** [comment]
@spew @shorea 

The [GetObjectMetadata](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L997) API on the AmazonS3Client automatically resolves the region of bucket by making a HEAD calls and caching the region of the bucket for future calls. Did you try initializing the TransferManager with the destination and see if it works ?

**Comment by spew** [comment]
Destination works, but it works poorly. Each copy request results in a WARN being printed out in S3V4AuthErrorRetryStrategy it also doubles the number of API calls and leads to throttling.

**Comment by spew** [comment]
Closing this PR and opening a new one with the source client approach.

**Pull request closed without merging**
